language: node_js
node_js: node

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - develop

install:
  - npm install
  - npm run generate
  - npm install -g nuxt

script:
  - echo "Skipping tests"
  - yarn generate
  - npm run generate
  - ls -al

deploy:
  provider: pages
  script: 
    - yarn generate
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: main
  local-dir: dist
  on:
    branch: develop